"""add creator content models

Revision ID: 00f2d1da315e
Revises: a7bef4bb4d7e
Create Date: 2026-08-27 13:17:10.521965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f2d1da315e'
down_revision: Union[str, Sequence[str], None] = 'a7bef4bb4d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_processing_status'), 'media', ['processing_status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_creator_id'), 'posts', ['creator_id'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_visibility'), 'posts', ['visibility'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('captions_url', sa.Text(), nullable=True),
    sa.Column('ai_caption', sa.Text(), nullable=True),
    sa.Column('copyright_status', sa.String(length=30), nullable=False),
    sa.Column('copyright_score', sa.Float(), nullable=True),
    sa.Column('is_monetized', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('watch_time_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_copyright_status'), 'videos', ['copyright_status'], unique=False)
    op.create_index(op.f('ix_videos_creator_id'), 'videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_videos_media_id'), 'videos', ['media_id'], unique=False)
    op.create_index(op.f('ix_videos_processing_status'), 'videos', ['processing_status'], unique=False)
    op.create_index(op.f('ix_videos_published_at'), 'videos', ['published_at'], unique=False)
    op.create_index(op.f('ix_videos_scheduled_at'), 'videos', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_video_type'), 'videos', ['video_type'], unique=False)
    op.create_index(op.f('ix_videos_visibility'), 'videos', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_visibility'), table_name='videos')
    op.drop_index(op.f('ix_videos_video_type'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_scheduled_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_published_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_processing_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_media_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_creator_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_copyright_status'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_posts_visibility'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_creator_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_media_processing_status'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
