"""creator analytics system

Revision ID: 177ae6f2a982
Revises: 523fbbd2373c
Create Date: 2026-05-30 19:10:01.867175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177ae6f2a982'
down_revision: Union[str, Sequence[str], None] = '523fbbd2373c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_analytics_events_id'), 'creator_analytics_events', ['id'], unique=False)
    op.create_table('creator_engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_engagement_id'), 'creator_engagement', ['id'], unique=False)
    op.create_table('creator_metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_metrics_snapshots_id'), 'creator_metrics_snapshots', ['id'], unique=False)
    op.create_table('creator_revenue_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('subscription_revenue', sa.Float(), nullable=True),
    sa.Column('affiliate_revenue', sa.Float(), nullable=True),
    sa.Column('sponsorship_revenue', sa.Float(), nullable=True),
    sa.Column('merchandise_revenue', sa.Float(), nullable=True),
    sa.Column('ticket_revenue', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_revenue_analytics_id'), 'creator_revenue_analytics', ['id'], unique=False)
    op.create_table('creator_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_views_id'), 'creator_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_views_id'), table_name='creator_views')
    op.drop_table('creator_views')
    op.drop_index(op.f('ix_creator_revenue_analytics_id'), table_name='creator_revenue_analytics')
    op.drop_table('creator_revenue_analytics')
    op.drop_index(op.f('ix_creator_metrics_snapshots_id'), table_name='creator_metrics_snapshots')
    op.drop_table('creator_metrics_snapshots')
    op.drop_index(op.f('ix_creator_engagement_id'), table_name='creator_engagement')
    op.drop_table('creator_engagement')
    op.drop_index(op.f('ix_creator_analytics_events_id'), table_name='creator_analytics_events')
    op.drop_table('creator_analytics_events')
    # ### end Alembic commands ###
