"""crypto wallets

Revision ID: 1fd083b98c34
Revises: d6cf783e23e2
Create Date: 2026-05-26 21:42:03.855963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd083b98c34'
down_revision: Union[str, Sequence[str], None] = 'd6cf783e23e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('wallet_type', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_crypto_wallets_id'), 'crypto_wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_wallets_id'), table_name='crypto_wallets')
    op.drop_table('crypto_wallets')
    # ### end Alembic commands ###
