"""sponsorship ecosystem

Revision ID: 20d7a8712c56
Revises: ef7b93ba57b3
Create Date: 2026-05-30 19:29:17.295400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7a8712c56'
down_revision: Union[str, Sequence[str], None] = 'ef7b93ba57b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_partnerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('partnership_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_partnerships_id'), 'brand_partnerships', ['id'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorships_id'), 'sponsorships', ['id'], unique=False)
    op.create_table('sponsorship_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_analytics_id'), 'sponsorship_analytics', ['id'], unique=False)
    op.create_table('sponsorship_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('contract_title', sa.String(), nullable=True),
    sa.Column('contract_url', sa.String(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('signed_by_creator', sa.String(), nullable=True),
    sa.Column('signed_by_brand', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_contracts_id'), 'sponsorship_contracts', ['id'], unique=False)
    op.create_table('sponsorship_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_deliverables_id'), 'sponsorship_deliverables', ['id'], unique=False)
    op.create_table('sponsorship_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_payments_id'), 'sponsorship_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorship_payments_id'), table_name='sponsorship_payments')
    op.drop_table('sponsorship_payments')
    op.drop_index(op.f('ix_sponsorship_deliverables_id'), table_name='sponsorship_deliverables')
    op.drop_table('sponsorship_deliverables')
    op.drop_index(op.f('ix_sponsorship_contracts_id'), table_name='sponsorship_contracts')
    op.drop_table('sponsorship_contracts')
    op.drop_index(op.f('ix_sponsorship_analytics_id'), table_name='sponsorship_analytics')
    op.drop_table('sponsorship_analytics')
    op.drop_index(op.f('ix_sponsorships_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('ix_brand_partnerships_id'), table_name='brand_partnerships')
    op.drop_table('brand_partnerships')
    # ### end Alembic commands ###
