"""live streaming ecosystem

Revision ID: 4468a3263ab6
Revises: ccaba350c43b
Create Date: 2026-05-31 20:31:17.084025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4468a3263ab6'
down_revision: Union[str, Sequence[str], None] = 'ccaba350c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('stream_key', sa.String(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_key')
    )
    op.create_index(op.f('ix_live_streams_id'), 'live_streams', ['id'], unique=False)
    op.create_table('stream_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('peak_viewers', sa.Integer(), nullable=True),
    sa.Column('unique_viewers', sa.Integer(), nullable=True),
    sa.Column('total_watch_time', sa.Float(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_gifts', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_analytics_id'), 'stream_analytics', ['id'], unique=False)
    op.create_table('stream_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_chat_messages_id'), 'stream_chat_messages', ['id'], unique=False)
    op.create_table('stream_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('gift_name', sa.String(), nullable=True),
    sa.Column('gift_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_gifts_id'), 'stream_gifts', ['id'], unique=False)
    op.create_table('stream_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('clip_url', sa.String(), nullable=True),
    sa.Column('start_second', sa.Integer(), nullable=True),
    sa.Column('end_second', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_highlights_id'), 'stream_highlights', ['id'], unique=False)
    op.create_table('stream_moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_moderators_id'), 'stream_moderators', ['id'], unique=False)
    op.create_table('stream_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_recordings_id'), 'stream_recordings', ['id'], unique=False)
    op.create_table('stream_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_reports_id'), 'stream_reports', ['id'], unique=False)
    op.create_table('stream_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_subscriptions_id'), 'stream_subscriptions', ['id'], unique=False)
    op.create_table('stream_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_viewers_id'), 'stream_viewers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_viewers_id'), table_name='stream_viewers')
    op.drop_table('stream_viewers')
    op.drop_index(op.f('ix_stream_subscriptions_id'), table_name='stream_subscriptions')
    op.drop_table('stream_subscriptions')
    op.drop_index(op.f('ix_stream_reports_id'), table_name='stream_reports')
    op.drop_table('stream_reports')
    op.drop_index(op.f('ix_stream_recordings_id'), table_name='stream_recordings')
    op.drop_table('stream_recordings')
    op.drop_index(op.f('ix_stream_moderators_id'), table_name='stream_moderators')
    op.drop_table('stream_moderators')
    op.drop_index(op.f('ix_stream_highlights_id'), table_name='stream_highlights')
    op.drop_table('stream_highlights')
    op.drop_index(op.f('ix_stream_gifts_id'), table_name='stream_gifts')
    op.drop_table('stream_gifts')
    op.drop_index(op.f('ix_stream_chat_messages_id'), table_name='stream_chat_messages')
    op.drop_table('stream_chat_messages')
    op.drop_index(op.f('ix_stream_analytics_id'), table_name='stream_analytics')
    op.drop_table('stream_analytics')
    op.drop_index(op.f('ix_live_streams_id'), table_name='live_streams')
    op.drop_table('live_streams')
    # ### end Alembic commands ###
