"""creator progression system

Revision ID: 523fbbd2373c
Revises: 71fc2b5b0a25
Create Date: 2026-05-30 18:56:23.147861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523fbbd2373c'
down_revision: Union[str, Sequence[str], None] = '71fc2b5b0a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('milestone_value', sa.Integer(), nullable=True),
    sa.Column('unlocked', sa.Boolean(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_achievements_id'), 'creator_achievements', ['id'], unique=False)
    op.create_table('creator_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('badge_slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_slug')
    )
    op.create_index(op.f('ix_creator_badges_id'), 'creator_badges', ['id'], unique=False)
    op.create_table('creator_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('reward_name', sa.String(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_rewards_id'), 'creator_rewards', ['id'], unique=False)
    op.create_table('creator_xp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('lifetime_xp', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_xp_id'), 'creator_xp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_xp_id'), table_name='creator_xp')
    op.drop_table('creator_xp')
    op.drop_index(op.f('ix_creator_rewards_id'), table_name='creator_rewards')
    op.drop_table('creator_rewards')
    op.drop_index(op.f('ix_creator_badges_id'), table_name='creator_badges')
    op.drop_table('creator_badges')
    op.drop_index(op.f('ix_creator_achievements_id'), table_name='creator_achievements')
    op.drop_table('creator_achievements')
    # ### end Alembic commands ###
