"""creator memberships

Revision ID: 71fc2b5b0a25
Revises: faf20a9b2433
Create Date: 2026-05-30 18:37:13.583847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fc2b5b0a25'
down_revision: Union[str, Sequence[str], None] = 'faf20a9b2433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('current_members', sa.Integer(), nullable=True),
    sa.Column('perks', sa.Text(), nullable=True),
    sa.Column('badge_name', sa.String(), nullable=True),
    sa.Column('badge_color', sa.String(), nullable=True),
    sa.Column('private_chat_access', sa.Boolean(), nullable=True),
    sa.Column('premium_content_access', sa.Boolean(), nullable=True),
    sa.Column('livestream_access', sa.Boolean(), nullable=True),
    sa.Column('event_access', sa.Boolean(), nullable=True),
    sa.Column('merchandise_discount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_memberships_id'), 'creator_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_memberships_id'), table_name='creator_memberships')
    op.drop_table('creator_memberships')
    # ### end Alembic commands ###
