"""read receipts

Revision ID: 8688bc2c7679
Revises: c44fdbc1839d
Create Date: 2026-05-15 17:16:47.242830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8688bc2c7679'
down_revision: Union[str, Sequence[str], None] = 'c44fdbc1839d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_seen', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'seen_at')
    op.drop_column('messages', 'is_seen')
    # ### end Alembic commands ###
