"""block system

Revision ID: 9b4d2736dc26
Revises: 8688bc2c7679
Create Date: 2026-05-16 15:40:04.762477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4d2736dc26'
down_revision: Union[str, Sequence[str], None] = '8688bc2c7679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('blocked_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_foreign_key(None, 'blocks', 'users', ['blocker_id'], ['id'])
    op.create_foreign_key(None, 'blocks', 'users', ['blocked_id'], ['id'])
    op.drop_column('blocks', 'blocked_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('blocked_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_column('blocks', 'blocked_id')
    # ### end Alembic commands ###
