"""creator economy

Revision ID: b37736a9de7d
Revises: 369857cb8327
Create Date: 2026-05-26 20:36:18.311516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37736a9de7d'
down_revision: Union[str, Sequence[str], None] = '369857cb8327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_posts_id'), 'creator_posts', ['id'], unique=False)
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subscription_price', sa.Integer(), nullable=True),
    sa.Column('is_verified_creator', sa.Boolean(), nullable=True),
    sa.Column('banner_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_profiles_id'), 'creator_profiles', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tips_id'), 'tips', ['id'], unique=False)
    op.add_column('communities', sa.Column('creator_only', sa.Boolean(), nullable=True))
    op.add_column('communities', sa.Column('subscription_required', sa.Boolean(), nullable=True))
    op.add_column('communities', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'communities', 'users', ['creator_id'], ['id'])
    op.add_column('users', sa.Column('pronouns', sa.String(), nullable=True))
    op.add_column('users', sa.Column('identity_tags', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verified_identity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_identity')
    op.drop_column('users', 'identity_tags')
    op.drop_column('users', 'pronouns')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'creator_id')
    op.drop_column('communities', 'subscription_required')
    op.drop_column('communities', 'creator_only')
    op.drop_index(op.f('ix_tips_id'), table_name='tips')
    op.drop_table('tips')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_creator_profiles_id'), table_name='creator_profiles')
    op.drop_table('creator_profiles')
    op.drop_index(op.f('ix_creator_posts_id'), table_name='creator_posts')
    op.drop_table('creator_posts')
    # ### end Alembic commands ###
