"""business platform system

Revision ID: cd820b96b05c
Revises: ebcc01129200
Create Date: 2026-06-01 13:42:26.194983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd820b96b05c'
down_revision: Union[str, Sequence[str], None] = 'ebcc01129200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_id'), 'brand_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_brand_profiles_slug'), 'brand_profiles', ['slug'], unique=True)
    op.create_table('audience_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('segment_name', sa.String(), nullable=False),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('fandoms', sa.Text(), nullable=True),
    sa.Column('estimated_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_id'), 'audience_segments', ['id'], unique=False)
    op.create_table('brand_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_analytics_id'), 'brand_analytics', ['id'], unique=False)
    op.create_table('brand_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_campaigns_id'), 'brand_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_brand_campaigns_slug'), 'brand_campaigns', ['slug'], unique=True)
    op.create_table('business_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_notifications_id'), 'business_notifications', ['id'], unique=False)
    op.create_table('business_revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('revenue_source', sa.String(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_revenues_id'), 'business_revenues', ['id'], unique=False)
    op.create_table('sponsored_communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_type', sa.String(), nullable=True),
    sa.Column('sponsorship_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsored_communities_id'), 'sponsored_communities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsored_communities_id'), table_name='sponsored_communities')
    op.drop_table('sponsored_communities')
    op.drop_index(op.f('ix_business_revenues_id'), table_name='business_revenues')
    op.drop_table('business_revenues')
    op.drop_index(op.f('ix_business_notifications_id'), table_name='business_notifications')
    op.drop_table('business_notifications')
    op.drop_index(op.f('ix_brand_campaigns_slug'), table_name='brand_campaigns')
    op.drop_index(op.f('ix_brand_campaigns_id'), table_name='brand_campaigns')
    op.drop_table('brand_campaigns')
    op.drop_index(op.f('ix_brand_analytics_id'), table_name='brand_analytics')
    op.drop_table('brand_analytics')
    op.drop_index(op.f('ix_audience_segments_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_brand_profiles_slug'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
