"""relationship ai system

Revision ID: ebcc01129200
Revises: 4468a3263ab6
Create Date: 2026-06-01 11:31:19.755727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcc01129200'
down_revision: Union[str, Sequence[str], None] = '4468a3263ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemistry_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=True),
    sa.Column('user_two_id', sa.Integer(), nullable=True),
    sa.Column('chemistry_score', sa.Float(), nullable=True),
    sa.Column('chemistry_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemistry_predictions_id'), 'chemistry_predictions', ['id'], unique=False)
    op.create_table('compatibility_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=False),
    sa.Column('user_two_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_scores_id'), 'compatibility_scores', ['id'], unique=False)
    op.create_table('relationship_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=True),
    sa.Column('user_two_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_events_id'), 'relationship_events', ['id'], unique=False)
    op.create_table('relationship_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=True),
    sa.Column('user_two_id', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_health_id'), 'relationship_health', ['id'], unique=False)
    op.create_table('relationship_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_insights_id'), 'relationship_insights', ['id'], unique=False)
    op.create_table('relationship_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=True),
    sa.Column('memory_key', sa.String(), nullable=True),
    sa.Column('memory_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_memories_id'), 'relationship_memories', ['id'], unique=False)
    op.create_table('relationship_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('love_language', sa.String(), nullable=True),
    sa.Column('personality_type', sa.String(), nullable=True),
    sa.Column('relationship_goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_relationship_profiles_id'), 'relationship_profiles', ['id'], unique=False)
    op.create_table('relationship_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_recommendations_id'), 'relationship_recommendations', ['id'], unique=False)
    op.create_table('social_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('connected_user_id', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_connections_id'), 'social_connections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_connections_id'), table_name='social_connections')
    op.drop_table('social_connections')
    op.drop_index(op.f('ix_relationship_recommendations_id'), table_name='relationship_recommendations')
    op.drop_table('relationship_recommendations')
    op.drop_index(op.f('ix_relationship_profiles_id'), table_name='relationship_profiles')
    op.drop_table('relationship_profiles')
    op.drop_index(op.f('ix_relationship_memories_id'), table_name='relationship_memories')
    op.drop_table('relationship_memories')
    op.drop_index(op.f('ix_relationship_insights_id'), table_name='relationship_insights')
    op.drop_table('relationship_insights')
    op.drop_index(op.f('ix_relationship_health_id'), table_name='relationship_health')
    op.drop_table('relationship_health')
    op.drop_index(op.f('ix_relationship_events_id'), table_name='relationship_events')
    op.drop_table('relationship_events')
    op.drop_index(op.f('ix_compatibility_scores_id'), table_name='compatibility_scores')
    op.drop_table('compatibility_scores')
    op.drop_index(op.f('ix_chemistry_predictions_id'), table_name='chemistry_predictions')
    op.drop_table('chemistry_predictions')
    # ### end Alembic commands ###
