"""ai onboarding

Revision ID: f2f51c914f35
Revises: 435911a3ce99
Create Date: 2026-05-28 11:56:59.639570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f51c914f35'
down_revision: Union[str, Sequence[str], None] = '435911a3ce99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('relationship_goal', sa.String(), nullable=True),
    sa.Column('social_energy', sa.String(), nullable=True),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('community_interests', sa.String(), nullable=True),
    sa.Column('emotional_style', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_onboarding_id'), 'ai_onboarding', ['id'], unique=False)
    op.create_table('ai_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('personality_summary', sa.Text(), nullable=True),
    sa.Column('interests_summary', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('emotional_profile', sa.String(), nullable=True),
    sa.Column('vibe_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_profiles_id'), 'ai_profiles', ['id'], unique=False)
    op.create_table('match_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=True),
    sa.Column('compatibility_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_insights_id'), 'match_insights', ['id'], unique=False)
    op.create_table('subscription_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('perks', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tiers_id'), 'subscription_tiers', ['id'], unique=False)
    op.add_column('communities', sa.Column('required_tier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'communities', 'subscription_tiers', ['required_tier_id'], ['id'])
    op.add_column('transactions', sa.Column('token_symbol', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('tx_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('blockchain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'blockchain')
    op.drop_column('transactions', 'tx_hash')
    op.drop_column('transactions', 'token_symbol')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'required_tier_id')
    op.drop_index(op.f('ix_subscription_tiers_id'), table_name='subscription_tiers')
    op.drop_table('subscription_tiers')
    op.drop_index(op.f('ix_match_insights_id'), table_name='match_insights')
    op.drop_table('match_insights')
    op.drop_index(op.f('ix_ai_profiles_id'), table_name='ai_profiles')
    op.drop_table('ai_profiles')
    op.drop_index(op.f('ix_ai_onboarding_id'), table_name='ai_onboarding')
    op.drop_table('ai_onboarding')
    # ### end Alembic commands ###
