"""creator revenue engine

Revision ID: fca45fd2634e
Revises: 20d7a8712c56
Create Date: 2026-05-31 13:35:47.653071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca45fd2634e'
down_revision: Union[str, Sequence[str], None] = '20d7a8712c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payout_method', sa.String(), nullable=True),
    sa.Column('payout_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_payouts_id'), 'revenue_payouts', ['id'], unique=False)
    op.create_table('revenue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.Float(), nullable=True),
    sa.Column('platform_fees', sa.Float(), nullable=True),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_reports_id'), 'revenue_reports', ['id'], unique=False)
    op.create_table('revenue_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('total_lifetime_revenue', sa.Float(), nullable=True),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('weekly_revenue', sa.Float(), nullable=True),
    sa.Column('daily_revenue', sa.Float(), nullable=True),
    sa.Column('pending_payouts', sa.Float(), nullable=True),
    sa.Column('total_payouts', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_snapshots_id'), 'revenue_snapshots', ['id'], unique=False)
    op.create_table('revenue_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('stream_name', sa.String(), nullable=False),
    sa.Column('stream_type', sa.String(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('yearly_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_streams_id'), 'revenue_streams', ['id'], unique=False)
    op.create_table('revenue_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_transactions_id'), 'revenue_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_transactions_id'), table_name='revenue_transactions')
    op.drop_table('revenue_transactions')
    op.drop_index(op.f('ix_revenue_streams_id'), table_name='revenue_streams')
    op.drop_table('revenue_streams')
    op.drop_index(op.f('ix_revenue_snapshots_id'), table_name='revenue_snapshots')
    op.drop_table('revenue_snapshots')
    op.drop_index(op.f('ix_revenue_reports_id'), table_name='revenue_reports')
    op.drop_table('revenue_reports')
    op.drop_index(op.f('ix_revenue_payouts_id'), table_name='revenue_payouts')
    op.drop_table('revenue_payouts')
    # ### end Alembic commands ###
